# Generated by Django 4.0.4 on 2022-05-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=254, null=True),
        ),
    ]
